name: Deploy to Gist
run-name: ${{ github.actor }} is deploying to Gist
on: [push]

jobs:
  to-gist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: YAML Parser
        # You may pin to the exact commit or the version.
        # uses: martinhaintz/ga-yaml-parser@ab949f97a775be9797b2e82235ba4eca9dea1c11
        uses: martinhaintz/ga-yaml-parser@v0.1.2
        with:
          # YAML file which should parsed
          file: ClashMi_Config.yaml

    
      - name: YAML Update Action
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          # YAML file which should be updated
          valueFile: ClashMi_Config.yaml
          createPR: false
          masterBranchName: main
          updateFile: false
          commitUserName: yitang823
          commitUserEmail: yitang823@gamil.com
          message: test
          changes: |
            {
              "ClashMi_Config.yaml":{
                "proxy-providers.Mitce.exclude-filter": "123" 
              }
            }

      - uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          # Set personal access token for updating gist.
          token: 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
          # Set id of the gist to be updated.
          gist_id: db143ab01b8ddd6d0075a574ec3a4f27
          # Set description of the gist.
          gist_description: 1
          # Set file name in the gist.
          gist_file_name: Config.yaml
          # Set path of the file to be deployed.
          file_path: /ClashMi_Config.yaml
          # Set file type of the file to be deployed.
          file_type: text
