- uses: actions/checkout@v3

- name: Deploy to Gist
  # You may pin to the exact commit or the version.
  # uses: exuanbo/actions-deploy-gist@47697fceaeea2006a90594ee24eb9cd0a1121ef8
  uses: exuanbo/actions-deploy-gist@v1.1.4
  with:
    # Set personal access token for updating gist.
    token: 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
    # Set id of the gist to be updated.
    gist_id: db143ab01b8ddd6d0075a574ec3a4f27
    # Set description of the gist.
    gist_description: # optional
    # Set file name in the gist.
    gist_file_name: # optional
    # Set path of the file to be deployed.
    file_path: /ClashMi_Config.yaml
    # Set file type of the file to be deployed.
    file_type: # optional, default is text
